<?php $_listing = $this->getListing(); ?>
<?php $_directory = $this->getDirectory(); ?>

<div class="account-login <?php echo $this->getElementClass(); ?>">
  <div class="page-title">
    <?php if($_listing): ?>
    <h1><?php echo $this->__('Do you own %s? Claim Your Business Profile for Free!',$_listing->getListingName()) ?></h1>
    <?php else: ?>
    <h1><?php echo $this->__('Create a FREE listing in "%s"!',$_directory->getContentHeading()) ?></h1>
    <?php endif; ?>
  </div>
  <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
  <?php /* Extensions placeholder */ ?>
  <?php echo $this->getChildHtml('customer.form.login.extra')?>
  <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
    <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>">
    <div class="col2-set">
      <div class="col-1 new-users">
        <div class="content block">
          <h2 class="block-title"><?php echo $this->__('New Users') ?></h2>
          <div class="block-content">
            <?php if($_listing): ?>
            <p><?php echo $this->__("Claiming your business profile has never been easier and it's absolutely FREE! If you are the legal owner of <strong>%s</strong>, click 'Create an Account' below to get started!",$_listing->getListingName()) ?></p>
            <?php else: ?>
            <p><?php echo $this->__("Adding your business profile to our <strong>%s</strong> directory has never been easier and it's absolutely FREE! If you are the legal owner of the business you want list, click 'Create an Account' below to get started!",$_directory->getContentHeading()) ?></p>
            <?php endif; ?>
          </div>
        </div>
      </div>
      <div class="col-2 registered-users">
        <div class="content block">
          <h2 class="block-title"><?php echo $this->__('Registered Users') ?></h2>
          <div class="block-content">
            <?php if($_listing): ?>
            <p><?php echo $this->__('If you have an account with us, please log in to claim your business profile.') ?></p>
            <?php else: ?>
            <p><?php echo $this->__('If you have an account with us, please log in to begin adding your business profile to <strong>%s</strong>.',$_directory->getContentHeading()) ?></p>
            <?php endif; ?>
            <ul class="form-list">
              <li>
                <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                  <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                </div>
              </li>
              <li>
                <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                <div class="input-box">
                  <input type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                </div>
              </li>
              <?php echo $this->getChildHtml('form.additional.info'); ?>
            </ul>
            <p class="required"><?php echo $this->__('* Required Fields') ?></p>
          </div>
        </div>
      </div>
    </div>
    <div class="col2-set">
      <div class="col-1 new-users">
        <div class="buttons-set">
          <button type="button" title="<?php echo $this->__('Create an Account') ?>" class="button" onclick="window.location='<?php echo $this->getCreateAccountUrl() ?>';"><span><span><?php echo $this->__('Create an Account') ?></span></span></button>
        </div>
      </div>
      <div class="col-2 registered-users">
        <div class="buttons-set"> <a href="<?php echo $this->getForgotPasswordUrl() ?>" class="f-left"><?php echo $this->__('Forgot Your Password?') ?></a>
          <button type="submit" class="button" title="<?php echo $this->__('Login') ?>" name="send" id="send2"><span><span><?php echo $this->__('Login') ?></span></span></button>
        </div>
      </div>
    </div>
  </form>
  <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('login-form', true);
    //]]>
    </script> 
</div>
