<?php $_listing = $this->getListing(); ?>
<?php if($this->canClaimProfile()): ?>
  <?php if(!$_listing->getCustomerId() || $_listing->getCustomerId() == 0): ?>
	<button type="button" id="button-<?php echo $_listing->getListingId(); ?>" title="Claim This Profile" class="button directory-button btn-claim-listing" onclick="setLocation('<?php echo $this->getUrl('*/profile/claim',array('listing_id'=>$_listing->getListingId())); ?>'); return false;"><span><span>Claim This Profile</span></span></button>              
  <?php elseif(Mage::helper('businessdirectory/listing')->canShowUpdateButton($_listing)): ?> 
	<button type="button" id="button-<?php echo $_listing->getListingId(); ?>" title="Update My Business Profile" class="button directory-button btn-update-listing" onclick="setLocation('<?php echo $this->getUrl('*/profile/update',array('listing_id'=>$_listing->getListingId())); ?>'); return false;"><span><span>Update My Profile</span></span></button>                                    
  <?php endif; ?>
<?php endif; ?>