<?php $_listing   = $this->getListing(); ?>
<?php $_directory = $this->getDirectory(); ?>
<?php $_helper    = $this->helper('businessdirectory'); ?>           
<?php $class = $_listing->getIsFeatured() ? 'featured-listing' : null; ?>
<div class="block-directory directory-heading <?php echo $class; ?> <?php echo $this->getElementClass(); ?>">              
  <div class="directory-data">
	<div class="listing-title">
	  <h1 <?php echo $this->addSchemaTag('name'); ?>><?php echo $_listing->getListingName() ?></h1>            
	</div>
	
	<div class="data-group">
	  <?php echo $_helper->renderAddress($_listing,null,$this->getShowCountry(),$this->getUseSchemaTags()) ?>
	  
	  <?php if($_listing->getListingContactName()): ?>
		<p><?php echo '<strong>Contact:</strong> '.$this->wrapWithSchemaTag($_listing->getListingContactName(),'employee') ?></p>
	  <?php endif; ?>
	  
	  <?php if($_listing->getListingPhone() && $_listing->getListingFax()): ?>
		<p><?php echo '<strong>Phone:</strong> '.$this->wrapWithSchemaTag($_listing->getListingPhone(),'phone').' | <strong>Fax:</strong> '.$this->wrapWithSchemaTag($_listing->getListingFax(),'fax'); ?></p>
	  <?php else: ?>
		<?php if($_listing->getListingPhone()): ?>
		  <p><?php echo '<strong>Phone:</strong> '.$this->wrapWithSchemaTag($_listing->getListingPhone(),'phone'); ?></p>
		<?php endif; ?>            
		<?php if($_listing->getListingFax()): ?>
		  <p><?php echo '<strong>Fax:</strong> '.$this->wrapWithSchemaTag($_listing->getListingFax(),'fax'); ?></p>
		<?php endif; ?>            
	  <?php endif; ?>
	  
	  <?php if($_listing->getListingWebsite() && $_listing->getListingEmail()): ?>
		<p><a href="#" rel="nofollow" onClick="setLocation('<?php echo $this->getUrl('*/*/redirect',array('listing_id' => $_listing->getListingId(),'link' => 'listing_website')) ?>');return false;" title="Visit the <?php echo $_listing->getListingName() ?> website!"><?php echo $this->wrapWithSchemaTag($_helper->renderUrl($_listing->getListingWebsite()),'url') ?></a> | <?php echo $this->wrapWithSchemaTag($_listing->getListingEmail(),'email') ?></p>
	  <?php else: ?>
		<?php if($_listing->getListingWebsite()): ?>
		  <p><a href="#" rel="nofollow" onClick="setLocation('<?php echo $this->getUrl('*/*/redirect',array('listing_id' => $_listing->getListingId(),'link' => 'listing_website')) ?>');return false;" title="Visit the <?php echo $_listing->getListingName() ?> website!"><?php echo $this->wrapWithSchemaTag($_helper->renderUrl($_listing->getListingWebsite()),'url') ?></a></p>
		<?php endif; ?>            
		<?php if($_listing->getListingEmail()): ?>
	  <p><?php echo $this->wrapWithSchemaTag($_listing->getListingEmail(),'email') ?></p>
		<?php endif; ?>            
	  <?php endif; ?>		 

	  <?php if($_listing->getLatitude() != 0 && $_listing->getLongitude() != 0): ?>
		<?php if($this->getUseSchemaTags()): ?>
		  <span itemprop="geo" itemscope itemtype="http://schema.org/GeoCoordinates">
			<?php echo $this->addSchemaTagMeta($_listing->getLatitude(),'latitude'); ?>
			<?php echo $this->addSchemaTagMeta($_listing->getLongitude(),'longitude'); ?>
		  </span>
		<?php endif; ?>
	  <?php endif; ?>
	</div>          
  </div>              
  <?php echo $this->getSocialHtml($_listing); ?>		                       
</div>