<?php $_directory = $this->getDirectory(); ?>
<?php $_helper    = Mage::helper('businessdirectory'); ?>
<?php $collection = $this->getCollection(); ?>

<?php if($collection->getSize() && $_directory->getShowMap() && $this->countGeocodedListings() > 0): ?>
  <script src="http://maps.google.com/maps/api/js?sensor=false" 
          type="text/javascript"></script>

  <div id="map" class="block <?php echo $this->getElementClass(); ?>" style="width: <?php echo $_directory->getMapWidth(); ?>px; height: <?php echo $_directory->getMapHeight(); ?>px;"></div>

  <script type="text/javascript">
    var locations = [
	  <?php $i=0; ?>
	  <?php foreach ($collection as $_listing): ?>
	    <?php if($_listing->getLatitude() != 0 && $_listing->getLongitude() != 0):?>
		  <?php if($_listing->getListingPhone()): ?>
			<?php $_listingPhone = '<p><strong>Phone:</strong> '.$_listing->getListingPhone().'</p>'; ?>
		  <?php else: ?>
			<?php $_listingPhone = null; ?>
		  <?php endif; ?> 
		  
		  <?php if($_listing->getListingWebsite()): ?>
			<?php $_listingWebsite = '<p><a href="#" rel="nofollow" onClick="setLocation(\''.$this->getUrl('businessdirectory/listing/redirect',array('listing_id' => $_listing->getListingId(),'link' => 'listing_website')).'\');return false;">'.$_helper->renderUrl($_listing->getListingWebsite()).'</a></p>'; ?>
		  <?php else: ?>
			<?php $_listingWebsite = null; ?>
		  <?php endif; ?>   	  	  
		
		  ['<?php echo $this->__(str_replace("'","\'",$_listing->getListingName().$_helper->renderAddress($_listing,null,$this->getShowCountry(),false).$_listingPhone.$_listingWebsite)); ?>', <?php echo $_listing->getLatitude() ?>, <?php echo $_listing->getLongitude() ?>, <?php echo $i++; ?>], 
		  <?php if($i===1): ?>
			<?php $centerLat = $_listing->getLatitude(); $centerLong = $_listing->getLongitude() ?>
		  <?php endif; ?>	
		<?php endif; ?>	
	  <?php endforeach; ?>
    ];

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 10,
      center: new google.maps.LatLng(<?php echo $centerLat; ?>, <?php echo $centerLong; ?>),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    });

    var infowindow = new google.maps.InfoWindow();

    var marker, i;

    for (i = 0; i < locations.length; i++) {  
      marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map
      });

      google.maps.event.addListener(marker, 'click', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));
    }	
  </script>
<?php endif; ?>